.TH DONUT.C 1 "November 2024" "Version 0.1a" "User Commands"
.SH NAME
donut.c \- A command-line tool for rendering animated donuts.

.SH SYNOPSIS
.B donut.c
[\fIOPTIONS\fR]

.SH DESCRIPTION
.B donut.c
is a command-line utility that renders an animated ASCII donut in the terminal. It is a lightweight and fun program designed to demonstrate 3D rendering techniques using simple ASCII art.

.SH OPTIONS
.TP
.B \-h, \-\-help
Display help information about
.B donut.c.
.TP
.B \-v, \-\-version
Display the version number of
.B donut.c.
.TP
.B \-s, \-\-speed
Specify the animation speed. Use a positive integer where higher numbers indicate faster rendering.

.SH EXAMPLES
.TP
Run the animated donut:
.PP
.nf
.B donut.c
.fi
.TP
Display the version number:
.PP
.nf
.B donut.c \-\-version
.fi
.TP
Run the animation with a speed factor of 3:
.PP
.nf
.B donut.c \-s 3
.fi

.SH FILES
.PP
No configuration files are required for
.B donut.c.

.SH AUTHOR
.PP
Developed by Aarav Darbari.

.SH REPORTING BUGS
.PP
Report bugs at: 
.br
\[la]https://github.com/aa830/homebrew-donut.c\[ra]

.SH COPYRIGHT
.PP
Copyright © 2024 Aarav Darbari. All rights reserved.

.SH SEE ALSO
.BR homebrew (1)

